name: Push Docker to Dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u yeranosyanvahan -p $DOCKER_PASSWORD
    - name: Building Fproxy
      run: docker build ./FProxy -t yeranosyanvahan/fproxy:$(date +%s)
    - name: Building Rproxy
      run: docker build ./RProxy -t yeranosyanvahan/rproxy:$(date +%s)
    - name: Pushing Fproxy
      run: docker push yeranosyanvahan/fproxy:$(date +%s)
    - name: Pushing Rproxy
      run: docker push yeranosyanvahan/rproxy:$(date +%s)
