name: Push Docker to Dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u yeranosyanvahan -p $DOCKER_PASSWORD
    - name: Building TLSTerminator
      run: docker build ./tlsterm -t yeranosyanvahan/tlsterminator:latest
    - name: Pushing TLSTerminator
      run: docker push yeranosyanvahan/tlsterminator:latest
